apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pacman-pvc
  namespace: pacman
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nfs-storageclass